"""update_yolo

Revision ID: c1fe5fed3b06
Revises: 4f7b93a7d7a7
Create Date: 2026-03-02 16:31:12.886034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fe5fed3b06'
down_revision: Union[str, Sequence[str], None] = '4f7b93a7d7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yolo', sa.Column('total_train_images', sa.Integer(), nullable=False))
    op.add_column('yolo', sa.Column('total_val_images', sa.Integer(), nullable=False))
    op.add_column('yolo', sa.Column('total_test_images', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yolo', 'total_test_images')
    op.drop_column('yolo', 'total_val_images')
    op.drop_column('yolo', 'total_train_images')
    # ### end Alembic commands ###
